name: aptible

on:
  push:
    branches: [main]
  workflow_dispatch: {}
  jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/deploy'
      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v4
        with:
          type: git
          app: stleech
          environment: leechst
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
